In [76]:
def show_book(figname):
    print(r"Siehe Abbildung §\ref{fig_XXX}§".replace("XXX", figname))
    plt.savefig(f"{figname}_snip.pdf")
    plt.show()

`begin math_basics`

In [4]:
27+39  # Grundrechenarten wie erwartet

66

In [5]:
3*7.5  # Punkt ist Dezimaltrennung

22.5

In [6]:
10/3  # Division liefert Gleitkommazahl

3.3333333333333335

In [3]:
2**10  # Potenzen mit ** Operator

1024

In [16]:
n = 42  # Variablen mit = gleichzeitig anlegen und zuweisen
n + 1/n

42.023809523809526

`end`

`begin math_advanced`

In [7]:
import math  # Modul mit mehr Funktionen und Konstanten
2*math.pi

6.283185307179586

In [9]:
math.sin(math.pi/2)

1.0

In [12]:
(1+5j)*1j  # Komplexe Zahlen mit imag. Einheit j

(-5+1j)

In [13]:
math.e**(1j*math.pi)  # (naja, fast)

(-1+1.2246467991473532e-16j)

`end`

`begin lists`

In [32]:
a = [5, 6, 4, 8, 9, 10]  # Listen in [] schreiben
a[2]  # mit [] Elemente auslesen, Zählung beginnt bei 0

4

In [33]:
a[2] = 7  # Elemente schreiben
a

[5, 6, 7, 8, 9, 10]

In [34]:
a[0:2]  # Teilliste (Slice) ausschneiden, oberer Index nicht inklusive

[5, 6]

In [35]:
a[:2]  # implizite untere oder obere Grenze

[5, 6]

In [40]:
a[0:6:2]  # Slice mit Schrittweite 2

[5, 7, 9]

In [41]:
a[::-1]

[10, 9, 8, 7, 6, 5]

In [42]:
[1, 2, 3, 4] + a  # + fügt Listen zusammen

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [43]:
a * 2  # Liste "wiederholen"

[5, 6, 7, 8, 9, 10, 5, 6, 7, 8, 9, 10]

`end`

In [48]:
import numpy as np
import numpy.random as nr
nr.seed(12315)
tt = np.linspace(np.pi/4, 3*np.pi/4, 10)
uu = 4 * np.sin(tt) + nr.random(len(tt))*0.2
R = 20
ii = uu / R + nr.random(len(tt))*0.01

In [47]:
uu

array([2.97524476, 3.37587692, 3.68798826, 3.90832773, 4.17092989,
       4.1714301 , 4.05022347, 3.64059144, 3.28113565, 2.87034957])

In [49]:
ii

array([0.15250661, 0.17071161, 0.18663681, 0.19770099, 0.20896332,
       0.21298383, 0.20475315, 0.19147461, 0.17039218, 0.15315638])

`begin array_intro`

In [51]:
import numpy as np  # Abkürzung des Importnamens
# np.array konvertiert normale Liste zu Numpy-Array
# Spannungsmessungen
uu = np.array([2.97, 3.37, 3.68, 3.90, 4.17, 4.17, 4.05, 3.64, 3.28, 2.87])
uu

array([2.97, 3.37, 3.68, 3.9 , 4.17, 4.17, 4.05, 3.64, 3.28, 2.87])

In [65]:
uu - 2  # Operationen mit Skalaren wirken elementweise

array([0.97, 1.37, 1.68, 1.9 , 2.17, 2.17, 2.05, 1.64, 1.28, 0.87])

In [55]:
# Strommessungen
ii = np.array([0.15, 0.17, 0.18, 0.19, 0.20, 0.21, 0.20, 0.19, 0.17, 0.15])
# Momentanleistung berechnen
pp = uu * ii  # Operationen mit Arrays wirken auch elementweise
pp

array([0.4455, 0.5729, 0.6624, 0.741 , 0.834 , 0.8757, 0.81  , 0.6916,
       0.5576, 0.4305])

In [66]:
# Durchschnittliche Leistung
(uu @ ii) / len(uu)  # Skalarprodukt mit @ Operator

0.66212

In [58]:
np.mean(pp)  # berechnet auch arithmetisches Mittel

0.66212

`end`

`begin plot_intro`

In [71]:
import matplotlib.pyplot as plt
tt = np.arange(0, 1.0, 0.1)  # Array der Messzeiten
tt

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [78]:
plt.plot(tt, uu, label='U [V]')  # Zeichne Spannungsverlauf
plt.plot(tt, ii, label='I [A]')  # Zeichne Stromverlauf
plt.legend()  # Legende anzeigen
show_book('ui_time')  #!

Siehe Abbildung §\ref{fig_ui_time}§


`end`

`begin plot_regression`

In [79]:
R = np.mean(uu/ii)
R

19.913677822005994

In [90]:
# Zeichne U gegen I als einzelne Punkte
plt.plot(ii, uu, marker='x', linestyle='')
# x-Werte für Regressionsgerade
ii_r = np.arange(0.14, 0.24, 0.02)
plt.plot(ii_r, R*ii_r)  # Regressionsgerade
# Achsenbeschriftungen
plt.xlabel('Strom [A]')
plt.ylabel('Spannung [V]')
plt.title('Strom- und Spannungsmessungen')  # Überschrift
plt.grid()  # Gitterhintergrund
show_book('ui_regression') #!

Siehe Abbildung §\ref{fig_ui_regression}§


`end`