# Einführungsbeispiel

In [1]:
# sorgt dafür, dass, wenn die letzte Zeile eine Zuweisung ist, deren Ergebnis auch ausgegeben wird
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'

In [2]:
import numpy as np
np.random.seed(1154)

`begin array_creation_1`

In [3]:
import numpy as np # Paket importieren

# Array-Analogon zur "normalen" range-Funktion
np.arange(4) # ganze Zahlen von 0 bis (exklusive) 4

array([0, 1, 2, 3])

In [4]:
np.arange(5, 13, 2) # ... 5 bis 13, Schrittweite: 2

array([ 5,  7,  9, 11])

In [5]:

# Werte von -1 bis inklusive 1; 5 Werte insgesamt (linear)
np.linspace(-1, 1, 5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [6]:

# Werte von 10**-1 bis 10**2;
# 4 Werte insgesamt (logarithmisch)
np.logspace(-1, 2, 4)

array([  0.1,   1. ,  10. , 100. ])

In [7]:

np.zeros(3) # drei Nullen

array([0., 0., 0.])

In [8]:
np.ones(4) # vier Einsen

array([1., 1., 1., 1.])

In [9]:
# array mit 5 Zufallszahlen zwischen 0 und 1
np.random.random(5) 

array([0.12615455, 0.35677722, 0.40587679, 0.76767964, 0.40780492])

`end array_creation_1`

`begin array_creation_2`

In [10]:
# 1d-array aus einer (unverschachtelten) Liste
x1 = np.array([ 1.5, 2.7, 0.9])
x1.shape

(3,)

In [11]:
#_
# 2d-array aus einer Liste von Listen
# innere Listen sind Zeilen
x2 = np.array([ [3, 4, 5], [8, 9, 10]])

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [12]:
x2.shape

(2, 3)

In [13]:
# Bedeutung von .shape:
# 2 Zeilen (Achse 0), 3 Spalten (Achse 1)
#_

In [14]:
#_
x3 = np.eye(3) # 3-mal-3-Einheitsmatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
x3.shape

(3, 3)

In [16]:
#_
# Diagonalmatrix 
x4 = np.diag([7, 6, 5])

array([[7, 0, 0],
       [0, 6, 0],
       [0, 0, 5]])

In [17]:
x4.shape

(3, 3)

In [18]:
#_
# random erwartet ein Argument (entspricht .shape)
x5 = np.random.random( (5, 4, 10) )
# Array zu groß für Anzeige
x5.shape

(5, 4, 10)

In [19]:
x6 = np.zeros( (30, 50, 10, 42) )
# Array zu groß und zu uninteressant für Anzeige
x6.shape

(30, 50, 10, 42)

`end array_creation_2`

### Laden und Speichern

`begin save_load_1`

In [20]:
# Pseudo-Daten erzeugen
x = np.zeros((10, 3))
#_
# Array im Text-Format speichern
np.savetxt("data.txt", x)
#_
# Array aus Text-Format laden
x = np.loadtxt("data.txt")
#_
# Array im CSV-Format speichern und
# Kommentar in erste Zeile schreiben
np.savetxt("data.csv", x, delimiter=',', 
           header="Zeit, Strom, Spannung")
#_
# Daten im CSV-Format laden und dabei erste Zeile ignorieren
x = np.loadtxt("data.csv", delimiter=',', skiprows=1)
#_
# Einen Array im Binärformat speichern und laden
np.save("data.npy", x)
x = np.load("data.npy")

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

`end save_load_1`

`begin array_indexation_0`

In [21]:
x = np.array([10, 20, 30, 40, 50])
x[0]

10

In [22]:
x[3]

40

In [23]:
x[-1]

50

In [24]:
x[-4]

20

`end array_indexation_0`

`begin array_indexation_1`

In [25]:
x =  np.array([10, 20, 30, 40, 50])
# Index:       0   1   2   3   4
# neg. Index:  -5  -4  -3  -2  -1

x[:]
x[None:None]
x[0:None]
x[0:None:1]

array([10, 20, 30, 40, 50])

In [26]:
#_
x[0:3]
x[0:3:1]
x[:3]
x[None:3]
x[:-2]

array([10, 20, 30])

In [27]:
#_
x[2:]
x[2:None]
x[-3:]
x[-3::1]

array([30, 40, 50])

In [28]:
#_
x[-1:]

array([50])

In [29]:
#_
x[-2:-1]

array([40])

In [30]:
#_
x[::2]

array([10, 30, 50])

In [31]:
#_
x[::-1]
x[None:None:-1]

array([50, 40, 30, 20, 10])

In [32]:
# Stop-Index ist exklusiv (nicht im Ergebnis enthalten)
x[-1:0:-1]

array([50, 40, 30, 20])

In [33]:
#_
x[-2:1:-1]
x[3:1:-1]

array([40, 30])

In [34]:
#_
x[::-2]

array([50, 30, 10])

In [35]:
#_
x[0:0]
x[4:2]
x[2:3:-1]

array([], dtype=int64)

`end array_indexation_1`

`begin multi_dim_indices_1`

In [36]:
x = np.array([[10, 20, 30], [40, 50, 60]])

array([[10, 20, 30],
       [40, 50, 60]])

In [37]:
# 2 Zeilen, 3 Spalten
x.shape

(2, 3)

In [38]:
# Ein einzelnes Element auswählen:
x[0, 0]

10

In [39]:
x[1, 2]

60

In [40]:
x[-1, 0]

40

`end multi_dim_indices_1`

`begin multi_dim_indices_2`

In [41]:
# Teilarray: alle Zeilen,
# Spalten bis (exklusive) Index 2
y = x[:, :2]

array([[10, 20],
       [40, 50]])

In [42]:
y.shape

(2, 2)

In [43]:
# erste Spalte auswählen (als 1d-Teilarray)
# Zeilenindex: alle, Spaltenindex: 0
z1 = x[:, 0]

array([10, 40])

In [44]:
#_
# z1 ist ein 1D-Array
z1.shape

(2,)

In [45]:
# erste Spalte auswählen (als 2D-Teilarray)
# Zeilenindex: alle,
# Spaltenindex: 0 bis (exklusive) 1
z2 = x[:, 0:1]

array([[10],
       [40]])

In [46]:
# zweite Zeile auswählen (als 2D-Teilarray)
# Zeilenindex: 1 bis (exklusive) 2
# Spaltenindex: alle
z3 = x[1:2, :]

array([[40, 50, 60]])

In [47]:
#_
# Achtung: z2 und z3 sind 2D-Arrays
z2.shape, z3.shape

((2, 1), (1, 3))

`end multi_dim_indices_2`

`begin multi_dim_indices_3`

In [48]:
x[0,0] = 100
x[-1, :] = np.arange(3)
x[0, 1:] = 42
x

array([[100,  42,  42],
       [  0,   1,   2]])

`end multi_dim_indices_3`

Beispiel nich benötigt:

`begin sequence_indices`

In [49]:
x =  np.array([10, 20, 30, 40, 50])
# Index:       0   1   2   3   4
# neg. Index:  -5  -4  -3  -2  -1

# Liste mit int-Zahlen
indices1 = [2, 0, 2, -1]
x[indices1]

array([30, 10, 30, 50])

In [50]:

# Liste mit bool-Werten
indices2 = [True, False, False, True, True]
x[indices2]

array([10, 40, 50])

In [51]:

# Bei bool-Indizierung erforderlich
len(indices2) == len(x)

True

`end sequence_indices`

### Verändern der Form

`begin reshape1`

In [52]:
x = np.array([[10, 20, 30], [40, 50, 60]])

array([[10, 20, 30],
       [40, 50, 60]])

In [53]:
x.transpose()
x.T

array([[10, 40],
       [20, 50],
       [30, 60]])

`end reshape1`

`begin reshape2`

In [54]:
x2 = x.reshape( (3, 2))
x2 = x.reshape(3, 2)

array([[10, 20],
       [30, 40],
       [50, 60]])

`end reshape2`

`begin reshape3`

In [55]:
x.reshape(6,)
x.flatten()

array([10, 20, 30, 40, 50, 60])

`end reshape3`

`begin reshape4`

In [56]:
# nur Zeilenanzahl (=2) wird angegeben
# Spaltenanzahl (=5) ergibt sich automatisch
np.arange(10).reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
#_
# Weil eine der Achsenlängen -1 sein darf
# kann man statt x.reshape(6) auch folgendes schreiben:
# (len(x) muss man dafür nicht wissen)
# -> äquivalent zu .flatten
x.reshape(-1)

array([10, 20, 30, 40, 50, 60])

`end reshape4`

`begin reshape5`

In [58]:
y1 = np.array([70, 80, 90])

array([70, 80, 90])

In [59]:
y1.shape

(3,)

In [60]:
#_
y2 = np.array([[70, 80, 90]])

array([[70, 80, 90]])

In [61]:
y2.shape

(1, 3)

In [62]:
#_
y1.T

array([70, 80, 90])

In [63]:
y2.T

array([[70],
       [80],
       [90]])

`end reshape5`

`begin combination1`

In [64]:
x = np.array([7, 8, 9, 10, 11, 12])
#_
x.reshape(3, -1)

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [65]:
#_
x.reshape(3, -1).T

array([[ 7,  9, 11],
       [ 8, 10, 12]])

In [66]:
#_
x.reshape(3, -1).T[:, 1:]

array([[ 9, 11],
       [10, 12]])

In [67]:
#_
x.reshape(3, -1).T[:, 1:].flatten()

array([ 9, 11, 10, 12])

`end combination1`

### Elementweises Rechnen

`begin calc1`

In [68]:
x = np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [69]:
x/2

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5]])

In [70]:
x + 1.6

array([[1.6, 2.6, 3.6],
       [4.6, 5.6, 6.6]])

In [71]:
x**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [72]:
x + x*0.1

array([[0. , 1.1, 2.2],
       [3.3, 4.4, 5.5]])

In [73]:
x - x

array([[0, 0, 0],
       [0, 0, 0]])

`end calc1`

`begin calc2`

In [74]:
y = np.array([10, 20, 30])
y.shape

(3,)

In [75]:
x + y

array([[10, 21, 32],
       [13, 24, 35]])

`end calc2`

Der folgende Schnipsel soll fehlerhaften Code darstellen. Damit das Notebook dennoch fehlerfrei durchläuft ist die problematische Zeile auskommentiert. Das Konversionsskript für die Schnipsel im Buch erkennt den speziellen Kommentar `#!` und filtert ihn raus.

`begin calc3`

In [76]:
#!x.T + y
print("ValueError: operands could not be broadcast together with shapes (3,2) (3,)") #!

ValueError: operands could not be broadcast together with shapes (3,2) (3,)


`end calc3`

### Views vs. Kopien

`begin views1`

In [77]:
q1 = np.arange(4)
# q2 ist ein View auf die Daten von q1
q2 = q1.reshape(2, -1)

array([[0, 1],
       [2, 3]])

In [78]:
# erste Spalte von q2 auswählen
# -> ebenfalls view
s = q2[:, 0]

array([0, 2])

In [79]:
#_
# Durch Rechenoperation wird Erstellung eines
# eigenen unabhängigen Arrays erzwungen -> Kopie
q3 = q2*1 

array([[0, 1],
       [2, 3]])

In [80]:
#_
# Veränderung von q1 bewirkt auch eine Veränderung von q2
q1[0] = 100
q2

array([[100,   1],
       [  2,   3]])

In [81]:
# und von s
s

array([100,   2])

In [82]:
#_
# ... aber nicht von q3
q3

array([[0, 1],
       [2, 3]])

`end views1`

`begin views2`

In [83]:
L1 = ["a", [50, 60, 70], "z"]
L2 = L1[1:] #:

[[50, 60, 70], 'z']

In [84]:
#_
L1[1][0] = 3
L2

[[3, 60, 70], 'z']

`end views2`

# Numpy-Indizierung von Arrays mit Arrays

### Kleines Einführungsbeispiel

`begin sophisticated_indexing1`

In [85]:
t = np.linspace(0, 10, 10000) # Zeit
u = np.sin(50*2*np.pi*t)*3 # el. Spannung (3V Amplitude)
u.shape

(10000,)

`end sophisticated_indexing1`

`begin sophisticated_indexing2`

In [86]:
x = np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [87]:
# Vergleich von Array und Skalar
x > 3

array([False, False, False, False,  True,  True,  True])

In [88]:
#_
y = np.array([0.5, 1, 2, 3, 0, 4, 5])
# Vergleich von zwei Arrays (mit gleicher Form)
x == y

array([False,  True,  True,  True, False, False, False])

`end sophisticated_indexing2`

`begin sophisticated_indexing3`

In [89]:
ii = x == y

array([False,  True,  True,  True, False, False, False])

In [90]:
ii.dtype

dtype('bool')

In [91]:
# automatische Umwandlung: bool -> int
z1 = ii*1

array([0, 1, 1, 1, 0, 0, 0])

In [92]:
z1.dtype

dtype('int64')

In [93]:
# automatische Umwandlung: bool -> float
z2 = ii*1.0

array([0., 1., 1., 1., 0., 0., 0.])

In [94]:
z2.dtype

dtype('float64')

`end sophisticated_indexing3`

In [95]:
np.random.seed(1019)

`begin sophisticated_indexing4`

In [96]:
x

array([0, 1, 2, 3, 4, 5, 6])

In [97]:
ii

array([False,  True,  True,  True, False, False, False])

In [98]:
x[ii]

array([1, 2, 3])

In [99]:
y

array([0.5, 1. , 2. , 3. , 0. , 4. , 5. ])

In [100]:
#_
# komplexeres Beispiel:
# (% ist der Modulo-Operator, liefert Divisionsrest)
x % 2

array([0, 1, 0, 1, 0, 1, 0])

In [101]:
x % 2 == 0

array([ True, False,  True, False,  True, False,  True])

In [102]:
# y eingeschränkt auf die Indizes bei denen x eine gerade Zahl ist
y[x % 2 == 0]

array([0.5, 2. , 0. , 5. ])

`end sophisticated_indexing4`

`begin sophisticated_indexing5`

In [103]:
x2d = np.array([[60, 50, 10], [30, 70, 20], [60, 50, 90]])

array([[60, 50, 10],
       [30, 70, 20],
       [60, 50, 90]])

In [104]:
x2d > 50

array([[ True, False, False],
       [False,  True, False],
       [ True, False,  True]])

In [105]:
x2d[x2d>50]

array([60, 70, 60, 90])

In [106]:
# Zum Vergleich:
x2d.flatten()

array([60, 50, 10, 30, 70, 20, 60, 50, 90])

In [107]:
x2d.flatten() > 50

array([ True, False, False, False,  True, False,  True, False,  True])

`end sophisticated_indexing5`

`begin sophisticated_indexing6`

In [108]:
# letzte Zeile (klassischer Index)
# Spaltenauswahl erfolgt über bool-Liste passender Länge
x2d[-1, [True, False, True]]

array([60, 90])

`end sophisticated_indexing6`

### Zurück zum Einführungsbeispiel

`begin sophisticated_indexing7`

In [109]:
t_active = t[u > 0.7]
t_active.shape

(4250,)

`end sophisticated_indexing7`

## Indizierung mit `int`-arrays

`begin int_arr_indexing1`

In [171]:
x = np.array([100, 110, 120, 130, 140])

array([100, 110, 120, 130, 140])

In [174]:
relevant_idcs1 = np.array([0, 3, 1])

array([0, 3, 1])

In [175]:
#_
x[relevant_idcs1]

array([100, 130, 110])

`end int_arr_indexing1`

`begin int_arr_indexing2`

In [113]:
len(x), len(relevant_idcs1)

(5, 3)

`end int_arr_indexing2`

`begin int_arr_indexing3`

In [114]:
# int-Liste anstatt int-Array verwenden:
x[[0, 2, 3]]

array([100, 120, 130])

In [115]:
#_
# Indizes wiederholen
x[[1, 2, 1, 2, 2, 3]]

array([110, 120, 110, 120, 120, 130])

`end int_arr_indexing3`

`begin int_arr_indexing4`

In [177]:
x2d = np.linspace(100, 180, 9).reshape(3, -1)

array([[100., 110., 120.],
       [130., 140., 150.],
       [160., 170., 180.]])

In [178]:
#_
# Zeilen auswählen mit Index-Liste 
x2d[[2, 0, 2], :]

array([[160., 170., 180.],
       [100., 110., 120.],
       [160., 170., 180.]])

In [179]:
#_
# Spalten auswählen mit Index-Liste 
x2d[:, [2, 0, 2]]

array([[120., 100., 120.],
       [150., 130., 150.],
       [180., 160., 180.]])

`end int_arr_indexing4`

`begin int_arr_indexing5`

In [180]:
#_
# Zeilen und Spalten auswählen mit Index-Liste 
x2d[[0, 1, 2], [0, 1, 2]]

array([100., 140., 180.])

In [181]:
x2d[[2, 0, 2], [2, 1, 0]]

array([180., 110., 160.])

In [182]:
# zum Vergleich nomal einzeln:
x2d[2, 2], x2d[0, 1], x2d[2, 0]

(180.0, 110.0, 160.0)

In [183]:
#_
# 2d-Index-Array für 2d-Daten-Array
idcs2 = np.array([2, 0, 2, 2, 1, 0]).reshape(2, -1)

array([[2, 0, 2],
       [2, 1, 0]])

In [123]:
x2d[idcs2[0, :], idcs2[1, :]]

array([180., 110., 160.])

In [124]:
#_
x2d[idcs2[0, :], idcs2[1, :]] *= 0.01

In [125]:
x2d

array([[100. ,   1.1, 120. ],
       [130. , 140. , 150. ],
       [  1.6, 170. ,   1.8]])

`end int_arr_indexing5`

# Numpy-Funktionen

In [126]:
# Temprorär die Anzahl der angezeigten Dezimalstellen herabsetzen
# (Platz im Buch sparen)

orig_print_options = np.get_printoptions()


np.set_printoptions(linewidth=70)

`begin functions1`

In [127]:
x = np.linspace(-1, 0.5, 5)

array([-1.   , -0.625, -0.25 ,  0.125,  0.5  ])

In [128]:
#_ 
np.around(x, 1)

array([-1. , -0.6, -0.2,  0.1,  0.5])

In [129]:
#_
# das letze Element ist "numerisch Null"
np.cos(x*np.pi)

array([-1.00000000e+00, -3.82683432e-01,  7.07106781e-01,
        9.23879533e-01,  6.12323400e-17])

In [130]:
#_

np.exp(x)

array([0.36787944, 0.53526143, 0.77880078, 1.13314845, 1.64872127])

In [131]:
#_
np.abs(x)

array([1.   , 0.625, 0.25 , 0.125, 0.5  ])

In [132]:
#_
np.sign(x)

array([-1., -1., -1.,  1.,  1.])

`end functions1`

`begin functions2`

In [133]:
# 31 macht Unterschied von Mittelwert
# und Median deutlich
x = np.array([0, 31, 2, 3, 4]) #:

array([ 0, 31,  2,  3,  4])

In [134]:
#_
# arithmetisches Mittel: (0+31+2+3+4)/5
np.mean(x)

8.0

In [135]:
#_
# der Wert, der nach dem sortieren in der Mitte liegt
np.median(x)

3.0

In [136]:
#_
np.min(x)

0

In [137]:
np.max(x)

31

In [138]:
#_
# 0 + 31 + 2 + 3 + 4
np.sum(x)

40

In [139]:
#_
# "nulltes" Element weglassen (sonst: 0)
# 31 · 2 · 3 · 4
np.prod(x[1:])

744

`end functions2`

`begin functions3`

In [140]:
np.cumsum(x)

array([ 0, 31, 33, 36, 40])

In [141]:
#_
np.cumprod(x[1:])

array([ 31,  62, 186, 744])

`end functions3`

`begin functions4`

In [142]:
# berechnet immer: "Element minus Vorgänger-Element"
np.diff(x)

array([ 31, -29,   1,   1])

In [143]:
# [31-0, 2-31, 3-2, 4-3]

`end functions4`

`begin functions5`

In [144]:
t = np.linspace(0, 10, 50) # Zeit
x = np.random.random(50) # "Messung"
x.shape


(50,)

In [145]:
#_
xdot = np.diff(x)/(t[1]-[0]) # Ableitung
xdot.shape

(49,)

`end functions5`

## Arrays vs. Matrizen (lineare Algebra)

`begin np_linalg1`

In [146]:
I = np.eye(3) # "Einheitsmatrix"

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [147]:
# beliebige "Matrix"
A = np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [148]:
#_
# Multiplikation der Arrays (elementweise)
I*A

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

`end np_linalg1`

`begin np_linalg2`

In [149]:
# "Zeilenvektor"
v = np.array([[10, 20, 30]])

array([[10, 20, 30]])

In [150]:
v.shape

(1, 3)

In [151]:
# Multiplikation mit Broadcasting
#_
# (3x3-"Matrix")*(1x3-"Zeilenvektor")
# nicht erlaubt in linearer Algebra
# numpy:
I*v

array([[10.,  0.,  0.],
       [ 0., 20.,  0.],
       [ 0.,  0., 30.]])

In [152]:
# 3x2-Array
B = A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [153]:
# (3x3-"Matrix")*(3x2-"Matrix")
# erlaubt in linearer Algebra, aber Fehler in NumPy:
#!I*B
print("ValueError: operands could not be broadcast together with shapes (3,3) (3,2)") 

ValueError: operands could not be broadcast together with shapes (3,3) (3,2)


`end np_linalg2`

In [154]:
v

array([[10, 20, 30]])

`begin np_linalg3`

In [155]:
# (3x3-Array) "mal" (3x3-Array)
I@A

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [156]:
# (3x3-Array) "mal" (3x2-Array)
I@B

array([[1., 2.],
       [4., 5.],
       [7., 8.]])

In [157]:
#_
# "Matrix" "mal" "Zeilenvektor" (nicht definiert)
#!I@v
print("ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)") #!

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)


In [158]:
#_
# "Matrix" "mal" "Spaltenvektor"
I@v.T

array([[10.],
       [20.],
       [30.]])

In [159]:
# mehrfache Hintereinanderausführung
A@A@I@v.T

array([[2280.],
       [5160.],
       [8040.]])

`end np_linalg3`

` begin np_linalg4`

In [160]:
A = np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
# aus v einen 1d-array machen
w = v.flatten()

array([10, 20, 30])

In [162]:
#_
# Jetzt sind beide Richtungen erlaubt.
A@w # w wird als Spaltenvektor interpretiert

array([140, 320, 500])

In [163]:
w@A # w wird als Zeilenvektor interpretiert

array([300, 360, 420])

`end np_linalg4`

`begin np_linalg5`

In [164]:
x = np.array([3, 2, 1])
w

array([10, 20, 30])

In [165]:
# Skalarprodukt (auch "Punktprodukt" genannt)
# 1d-Arrays interpretiert als "Zeile mal Spalte"
x@w

100

In [166]:
# dyadisches Produkt ("Spalte mal Zeile")
x.reshape(3, 1)@w.reshape(1, 3)

array([[30, 60, 90],
       [20, 40, 60],
       [10, 20, 30]])

`end np_linalg5`

In [167]:
q = np.matrix(A)
type(v)

numpy.ndarray

In [168]:
# Erzeugung der Schnipsel

!python3 /home/ck/projekte/2020_pfifd/repo/pfifd/nbsnippets.py /home/ck/projekte/2020_pfifd/repo/pfifd/code/kap_numpy/kapitel_numpy.ipynb

Extracting snippets in /home/ck/projekte/2020_pfifd/repo/pfifd/code/kap_numpy/kapitel_numpy.ipynb
Extracting snippets: array_creation_1, array_creation_2, save_load_1, array_indexation_0, array_indexation_1, multi_dim_indices_1, multi_dim_indices_2, multi_dim_indices_3, sequence_indices, reshape1, reshape2, reshape3, reshape4, reshape5, combination1, calc1, calc2, calc3, views1, views2, sophisticated_indexing1, sophisticated_indexing2, sophisticated_indexing3, sophisticated_indexing4, sophisticated_indexing5, sophisticated_indexing6, sophisticated_indexing7, int_arr_indexing1, int_arr_indexing2, int_arr_indexing3, int_arr_indexing4, int_arr_indexing5, functions1, functions2, functions3, functions4, functions5, np_linalg1, np_linalg2, np_linalg3, np_linalg4, np_linalg5
Done
