In [1]:
# sorgt dafür, dass, wenn die letzte Zeile eine Zuweisung ist, deren Ergebnis auch ausgegeben wird
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'

`begin variablen1`

In [72]:
X = 123 # globale Variable

def func1():
    print(X) # lesender Zugriff auf globale Variable
    

def func2():
    X = 789 # Schreibzugriff -> Name `X` wird lokal
    print(X) # lesender Zugriff auf lokale Variable
    
func1()

123


In [3]:
func2()

789


`end variablen1`

`begin variablen2`

In [4]:
def func3():
    print(X) # lesender Zugriff 
    X = 789 # Schreibzugriff -> Name `X` wird lokal
    print(X) # lesender Zugriff
    
#!func3()
print("UnboundLocalError: local variable 'X' referenced before assignment") #!

UnboundLocalError: local variable 'X' referenced before assignment


`end variablen2`

`begin indextricks1`

In [5]:
from numpy import r_, c_

In [6]:
r_[0:20:3] # Abk. für np.arange(start, stop, step)

array([ 0,  3,  6,  9, 12, 15, 18])

In [7]:
r_[0:12:7j] # Abk. für np.linspace(start, stop, N)

array([ 0.,  2.,  4.,  6.,  8., 10., 12.])

`end indextricks1`

`begin indextricks2`

In [8]:
x = r_[3, 4, 5, 100] # Abk. für np.array(...)

array([  3,   4,   5, 100])

In [9]:
y = r_[0, x, [7, 8], 1:4 ] # einfaches zusammenfügen

array([  0,   3,   4,   5, 100,   7,   8,   1,   2,   3])

`end indextricks2`

`begin indextricks3`

In [10]:
c_[x, 3*x, range(4), 10:14, [21, 22, 23, 24]]

array([[  3,   9,   0,  10,  21],
       [  4,  12,   1,  11,  22],
       [  5,  15,   2,  12,  23],
       [100, 300,   3,  13,  24]])

`end indextricks3`

`begin indextricks4`

In [11]:
type(r_) # RClass steht für Row-Class, CClass analog

numpy.lib.index_tricks.RClass

`end indextricks4`

In [12]:
import importlib

In [13]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


`begin special_modules1`

In [14]:
#!import this
# importlib.reload(this) #!
# Standardmäßig keine Ausgabe, um Pointe nicht zu verderben #!

`end special_modules1`

`begin special_modules2`

In [15]:
import antigravity

`end special_modules2`

`begin special_modules3`

In [16]:
import os
import sys
os.path.abspath(this.__file__)

'/home/ck2/miniconda3/envs/base38/lib/python3.8/this.py'

In [17]:
os.path.abspath(antigravity.__file__)

'/home/ck2/miniconda3/envs/base38/lib/python3.8/antigravity.py'

`end special_modules3`

In [18]:
# leeres Modul anlegen
!touch human_challenges_solved.py

`begin reload1`

In [19]:
import human_challenges_solved

# Inzwischen gab es Änderungen am Code ... -> Neu laden!

import importlib
importlib.reload(human_challenges_solved)
pass #!

`end reload1`

`begin lambdify1`

In [20]:
import sympy as sp
import numpy as np

a, x = sp.symbols("a, x")
# a-abhängige Matrix einsetzen:
M = sp.Matrix([x, a*x**2])
# unproblematischen Wert für a einsetzen
M1 = M.subs(a, 1)
f1 = sp.lambdify(x, M1)
res1 = f1(np.array([1, 2, 3]))

array([[[1, 2, 3]],

       [[1, 4, 9]]])

`end lambdify1`

In [21]:
res = """\
array([[array([1, 2, 3])],
       [0]], dtype=object)
"""
pass

`begin lambdify2`

In [22]:
# problematischen Wert für a einsetzen
M0 = M.subs(a, 0)
f0 = sp.lambdify(x, M0)
# vermeide DeprecationWarning in Ausgabe -> nicht ausführen sondern nur Ergebnis anzeigen #!
#!res0 = f0(np.array([1, 2, 3]))
print(res)

array([[array([1, 2, 3])],
       [0]], dtype=object)



`end lambdify2`

`begin lambdify3`

In [23]:
# "Nahrhafte" Null einfügen (x - x)
M0[1] = sp.Add(M0[1], x, - x, evaluate=False)

In [24]:
M0

Matrix([
[         x],
[-x + x + 0]])

In [25]:
f0 = sp.lambdify(x, M0)
res0 = f0(np.array([1, 2, 3]))

array([[[1, 2, 3]],

       [[0, 0, 0]]])

`end lambdify3`

`begin lambdify4`

In [26]:
res0.shape

(2, 1, 3)

`end lambdify4`

`begin lambdify5`

In [27]:
res1.squeeze()

array([[1, 2, 3],
       [1, 4, 9]])

`end lambdify5`

`begin solve1`

In [28]:
import sympy as sp
x, y = sp.symbols("x, y")

# skalare Gleichung mit 2 Lösungen -> Liste
sp.solve(x**2-4)

[-2, 2]

In [29]:

# Gleichungssystem mit 1 Lösung -> dict
sp.solve([x-4, y-9])

{x: 4, y: 9}

In [30]:

# Gleichungssystem mit 2 Lösungen -> Liste mit dicts
sp.solve([x**2-4, y**2-9])

[{x: -2, y: -3}, {x: -2, y: 3}, {x: 2, y: -3}, {x: 2, y: 3}]

`end solve1`

`begin solve2`

In [31]:
sp.solve(x**2-4, dict=True)

[{x: -2}, {x: 2}]

In [32]:

sp.solve([x-4, y-9], dict=True)

[{x: 4, y: 9}]

`end solve2`

`begin broadcasting1`

In [33]:
x = np.arange(3)+100

array([100, 101, 102])

In [34]:
y = np.arange(3).reshape(1, -1) # 1 Zeile, passende Spaltenzahl

array([[0, 1, 2]])

In [35]:
# 1D-Array + Zeile = Zeile -> vermutlich erwartet
x + y

array([[100, 102, 104]])

`end broadcasting1`

`begin broadcasting2`

In [36]:
# 1D-Array + Spalte = Matrix -> vermutlich nicht beabsichtigt
x + y.T

array([[100, 101, 102],
       [101, 102, 103],
       [102, 103, 104]])

`end broadcasting2`

`begin booltricks1`

In [37]:
for i in range(3):
    x = i if i < 2 else "zu groß"
    print(x)

0
1
zu groß


`end booltricks1`

`begin booltricks2`

In [38]:
data = None # zum Beispiel aus Funktionsaufruf
msg = data or "Keine Daten erhalten!"
print(msg)

Keine Daten erhalten!


In [39]:
for i in range(3):
    msg = ("klein", "groß")[i > 1]
    print(msg)

klein
klein
groß


`end booltricks2`

`begin backslash1`

In [63]:
len("\n"), len("\f"), len("\p")

(1, 1, 2)

In [65]:
print("\frac{\pi}{2}") # `\f` wird missinterpretiert

rac{\pi}{2}


`end backslash1`

`begin backslash2`

In [67]:
len("\\n"), len("\\f"), len("\\p")

(2, 2, 2)

In [66]:
print("\\frac{\\pi}{2}")

\frac{\pi}{2}


`end backslash2`

`begin backslash3`

In [69]:
len(r"\n"), len(r"\f"), len(r"\p")

(2, 2, 2)

In [68]:
print(r"\frac{\pi}{2}")

\frac{\pi}{2}


`end backslash3`

In [70]:
!python3 ../../nbsnippets.py kapitel_fallstricke.ipynb

Extracting snippets in kapitel_fallstricke.ipynb
Extracting snippets: variablen1, variablen2, indextricks1, indextricks2, indextricks3, indextricks4, special_modules1, special_modules2, special_modules3, reload1, lambdify1, lambdify2, lambdify3, lambdify4, lambdify5, solve1, solve2, broadcasting1, broadcasting2, booltricks1, booltricks2, backslash1, backslash2, backslash3
Done


In [71]:
os.path.split?